name: Mirror to Gitee
on:
  push:
    branches: [main]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git push https://oauth2:${{ secrets.GITEE_MIRROR_TOKEN }}@gitee.com/no-memes/no-memes.git "refs/heads/*:refs/heads/*" "refs/tags/*:refs/tags/*" --force
